##########################################
### VARIABLES
##########################################
    # The following variables are being defined/used during testing. 
    # This file and the following variables work with the 
    # VS Code "Rest Client extension" which can be found here:
    # https://github.com/Huachao/vscode-restclient

@host = http://gated-woocommerce.local
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9nYXRlZC13b29jb21tZXJjZS5sb2NhbCIsImlhdCI6MTU3ODUwMDAwNSwibmJmIjoxNTc4NTAwMDA1LCJleHAiOjE1NzkxMDQ4MDUsImRhdGEiOnsidXNlciI6eyJpZCI6IjMzNDEifX19.XmZfZ6GjPEUiZsk3T-_HFeV_DP5xZbwbja2fx2d5SxI

# @host = http://gatedsite1.visagedevsite.info
# @token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9nYXRlZHNpdGUxLnZpc2FnZWRldnNpdGUuaW5mbyIsImlhdCI6MTU3MDcyODg2NCwibmJmIjoxNTcwNzI4ODY0LCJleHAiOjE1NzEzMzM2NjQsImRhdGEiOnsidXNlciI6eyJpZCI6IjMzNDEifX19.l-BtIqAmI6sNuCILhfy6YPPzVx9mMX8UG2cS8qdTYIg

# @host = http://bncarvanadev.wpengine.com
# @token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9ibmNhcnZhbmFkZXYud3BlbmdpbmUuY29tIiwiaWF0IjoxNTcxNjc5NTEyLCJuYmYiOjE1NzE2Nzk1MTIsImV4cCI6MTU3MjI4NDMxMiwiZGF0YSI6eyJ1c2VyIjp7ImlkIjoiMzM0MSJ9fX0.SbH8RBT0Yv82tl9U0vfXke37Cy70JROiYULpSCfYwNw

@username = mikegunn
@email = mike2@darngood.io
@name = API TEST
@first_name = Michael
@last_name = Gunningston
@address_1 = 512 Main Blvd
@address_2 = apt B
@city = New Brunswick
@state = NJ
@zip = 19106
@phone = 7775558888
@coupon_code = createcoupon
@password = Password123!&*
@userid = 3352
@carvanauid = C2654133-19A1-4AF8-ABEA-2D3920F65B28


########################################################
### GET A TOKEN FOR USERNAME AND PASSWORD 
##########################################
    # We are using the "JWT Authentication for the WP REST API" plugin, which can be found here:
    # https://github.com/Tmeister/wp-api-jwt-auth
    # Supply the endpoint with a (previously created) WordPress username and
    # password to get a JWT Token which can be stored/used in all subsequent API calls. 

    # Sample endpoint: POST http://gatedsite1.visagedevsite.info/wp-json/jwt-auth/v1/token/

POST {{host}}/wp-json/jwt-auth/v1/token/ HTTP/1.1
content-type: application/json

{
    "username": "apitest",
    "password": "Zpqb40waPqvg1j@a6FUia$V#"
}


##########################################
### GET ALL USERS
##########################################
    # This will return all WP Users.
    # By default, this endpoint will only return max 100 users. 
    # This was changed to 1000, but can be overridden with the 
    # 'custom_per_page' parameter. 

    # Sample endpoint: GET http://gatedsite1.visagedevsite.info/wp-json/wp/v2/users

GET {{host}}/wp-json/wp/v2/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

# {
#     "custom_per_page": "100"
# }



##########################################
### GET A USER
##########################################
    # By supplying a the USER ID at the end of this endpoint
    # the data for a specific user will be returned. 

    # Sample endpoint: GET http://gatedsite1.visagedevsite.info/wp-json/wp/v2/users/100

GET {{host}}/wp-json/wp/v2/users/{{userid}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


##########################################
### CREATE A USER
##########################################
    # This will create a new User in WP. 
    # The following fields are required:
        # email
        # username -- this should be same as email
        # password
    # The following fields are optional:
        # first_name 
        # last_name
        # carvana_uid
        # address_1
        # address_2
        # city
        # state
        # zip
        # phone
        # coupons 

    # To create a coupon with this call, supply the 'coupons' field with an array
    # of parameters. 'coupon_code' must be set to "createcoupon". The following parameters 
    # are optional:
        # coupon_status (by default this will be set to 'registered' unless specified)
        # vehicle_id
        # is_confirmed   

    # Sample endpoint: POST http://gatedsite1.visagedevsite.info/wp-json/wp/v2/users
    
POST {{host}}/wp-json/wp/v2/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "username":     "{{email}}",
    "email":        "{{email}}",
    "password":     "{{password}}",
    "first_name" :  "{{first_name}}",
    "last_name" :   "{{last_name}}",
    "address_1" :   "{{address_1}}",
    "address_2" :   "{{address_2}}",
    "city":         "{{city}}",
    "state":        "{{state}}",
    "zip":          "{{zip}}",
    "phone":        "{{phone}}",
    "coupons": {
        "coupon_status": "cancelled",
        //"is_confirmed": "yes",
        //"vehicle_id": "12345"
        "coupon_code": "f606dae8fb461b6bcf53347c671af416-1573681686-3352"
    }
}

##########################################
### UPDATE A USER
##########################################
    # This endpoint allows for the same parameters as above.
    # However, you need to supply the USER ID in the url in order to 
    # update the correct user.

    # Managing coupons is handled through the "coupons" field by
    # supplying an array of the following optional fields:
        # 'coupon_code'
        # 'coupon_status'
        # 'is_confirmed'
        # 'vehicle_id'

    # To create a coupon, "coupon_code" must be set to "createcoupon".
    # To edit a coupon, "coupon_code" must be set to a valid coupon code.

    # The following parameters are optional when creating or updating a coupon:
        # coupon_status (when creating, this will be set to 'registered' unless specified)
        # vehicle_id
        # is_confirmed

    # Use the "is_confirmed" field to track that a coupon is "confirmed" from 
    # Carvana's standpoint. This will allow us to retain the "confirmed" state regardless
    # of subsequent status changes. 

    # Sample endpoint: POST http://gatedsite1.visagedevsite.info/wp-json/wp/v2/users/100

POST {{host}}/wp-json/wp/v2/users/{{userid}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    //"first_name" :  "{{first_name}}",
    //"last_name" :   "{{last_name}}",
    //"address_1" :   "{{address_1}}",
    //"address_2" :   "{{address_2}}",
    //"city":         "{{city}}",
    //"state":        "{{state}}",
    //"zip":          "{{zip}}",
    //"phone":        "{{phone}}",
    "coupons": {
        "coupon_status": "cancelled",
        //"vehicle_id": "111111111",
        //"is_confirmed": false,
        "coupon_code": "f606dae8fb461b6bcf53347c671af416-1578951661-3352"
        //"coupon_code": "createcoupon"
    }
}

##########################################
### DELETE A USER
##########################################
    # This endpoint may not be necessary, but was useful during testing.
    # You must supply the USER ID in the URL, and the following
    # parameters are required as well:
        # force -- needs to be set to "true"
        # reassign -- the ID of an administrator user - this is 
            # meant to reassign any Posts to another user (though that isn't 
            # actually relevant to us).

    # Sample endpoint: DELETE http://gatedsite1.visagedevsite.info/wp-json/wp/v2/users/100

DELETE {{host}}/wp-json/wp/v2/users/{{userid}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "force" : "true",
    "reassign" : "3339"
}


##########################################
### GET USER BY CARVANA UID
##########################################
    # This endpoint will get the User by their Carvana UID. 
    # This endpoint can be used to get a User by any of their meta fields,
    # by swapping out the 'filter[meta_key]' value for another meta key. 

    # Sample endpoint: GET http://gatedsite1.visagedevsite.info/wp-json/wp/v2/users?filter[meta_key]=carvana_uid&filter[meta_value]=C2654133-19A1-4AF8-ABEA-2D3920F65B28

GET {{host}}/wp-json/wp/v2/users?filter[meta_key]=carvana_uid&filter[meta_value]={{carvanauid}}
content-type: application/json
Authorization: Bearer {{token}}



###############################################################
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

# THE FOLLOWING ENDPOINTS ARE INCLUDED FOR TESTING PURPOSES ONLY.
# THEY ARE CURRENTLY BEING USED FOR DEVELOPMENT PURPOSES ONLY AND 
# THE DATA SHOULD NOT BE EXPECTED TO BE ACCURATE / RELEVANT. 

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
###############################################################





##########################################
### GET A WOOCOMMERCE COUPON
##########################################

GET {{host}}/wp-json/wc/v3/coupons/590
Content-Type: application/json
Authorization: Bearer {{token}}


##########################################
### GET A WOOCOMMERCE CUSTOMER
##########################################

GET {{host}}/wp-json/wc/v3/customers/{{userid}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


##########################################
### LIST ALL API ENDPOINTS
##########################################
    # This is a default, non-authenticated endpoint of the WP REST API.
    # It will return endpoints for all available API calls.
    # It should not be needed, but was used for development only. 

GET http://gated-woocommerce.local/wp-json